version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - "8086:8086"
    networks:
      - link

  telegraf:
    image: telegraf:1.19
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - link

  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      - link
  sync_influxdb:
    image: ivandecharbo/sync-influxdb:latest
    container_name: sync_influxdb
    env_file:
      - .env
    volumes:
      - ./code/data:/app/data
    depends_on:
      - influxdb
      - modbus-server
    networks:
      - link  
  modbus-server:
    image: ivandecharbo/modbus-server:latest
    container_name: modbus-server
    env_file:
      - .env
    volumes:
      - ./code/data:/app/data
    ports:
      - "1502:1502"
    networks:
      - link

  
volumes:
  grafana-storage:
  influxdb-storage:


networks:
  link:
